### ISSUE TITLE
Only passing length to any.word breaks

### ISSUE THREAD

**Issue by richardson-trevor** [travi/any#246]
Since we started defaulting to a given number of syllables, we aren't able to conform to the any spec that only allows one or the other. We should check if `length` is passed and if so, don't default to the # of syllables.

**Comment by travi** [comment]
Makes sense. Do we have existing places where we are using `length`, or is this a newish need?

**Comment by richardson-trevor** [comment]
I was going to use it, then realized when I tried that it caused problems because we were attempting to send both length and # syllables. I forget what the error output was, but it wouldn't allow it. It essentially unnecessarily took away functionality that you had supported before.

**Comment by richardson-trevor** [comment]
I may get a PR out for you tomorrow morning (no pressing need right now, but shouldn't take long).

**Comment by travi** [comment]
Makes sense. Sounds like easy logic to encapsulate in `any.word()`. 

Sounds like you'll get to a PR long before is her around to making the change, so I'd recommend commiting as a `fix` based on your point about accidentally blocking previously working behavior.
